language: node_js
node_js:
  - '10'
env:
  - JWT_SECRET=JWT_SECRET
cache:
  directories:
    - node_modules
script:
  - cd frontend && npm i && cd ../backend && npm i && cd .. && npm test
# on:
# branch: master
